#!/bin/bash
# $Id$
#
# Archive all directories symlinked under $ARCHIVE_PATHS to the $ARCHIVE_DIR
# directory using the name of the symlink as the compressed tarball's filename.
# Directories or files listed in the ARCHIVE_EXCLUSIONS file will be skipped.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/sbin.bash

check_arg_count ${0} ${#} 0 0 '' ${1}

# With each symlink in the archive-paths/ directory, process the link's name
# and target (linkpath).
while read linkname linkpath ; do
    # Format archive filename.
    linkname=$(basename "${linkname}")
    archive_file="${ARCHIVE_DIR}/${linkname}.tgz"
    
    # Prepare archive file permissions before creating.
    touch ${archive_file}
    chmod u=rw,g=r,o= ${archive_file}
    
    # Create (compressed) archive file.
    tar --create --exclude-from "${ARCHIVE_EXCLUSIONS}" --file "${archive_file}" \
        --gzip --preserve-permissions "${linkpath}" 2>/dev/null
done < <(find "${ARCHIVE_PATH_DIR}/" -type l -printf '%p %l\n' 2>/dev/null)
