#!/bin/bash
#
# "Backup" the named file or files by making copies of them using each file's
# last modified date (yyyymmdd) as the extension.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/bin.bash"

check_arg_count ${0} ${#} 1 -1 '<file>[...]' ${1}

while [ -n "${1}" ] ; do
    original_file_path="${1}"
    original_file_name=$(basename "${original_file_path}")
    original_directory=$(dirname "${original_file_path}")

    # Is there another way to find the absolute directory path?
    absolute_path=$(cd "${original_directory}"; pwd)

    # Use the original modification time of the file as its YYYYMMDD extension.
    modification_time=$(stat --format=%Y "${original_file_path}")
    date_extension=$(date --date @${modification_time} +%Y%m%d)

    # Pick a unique backup file name, in case the backup name already exists.
    backup_file_name="${original_file_name}.${date_extension}"
    backup_file_name=$(unique-name "${absolute_path}" "${backup_file_name}")

    cp "${original_file_path}" "${absolute_path}/${backup_file_name}"

    # Backup file shouldn't be executable.
    chmod --silent -x "${absolute_path}/${backup_file_name}"

    shift
done
