#!/bin/bash
#
# Quickly report the status of all known Subversion projects.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/bin.bash"

check_arg_count ${0} ${#} 0 0 '' ${1}

curdir=''
topsvndirs=''

# Find the top-level directory for all Subversion project sandboxes.
for svndir in $(find / ${FIND_PATH_EXCLUDE} -or ${FIND_SVN_PATH_EXCLUDE} -or -type d -name '.svn' -printf '%h\n' 2>/dev/null | sort) ; do
    match=$(expr "${svndir}" : "${curdir}")

    if [ $match -eq 0 ] ; then
        curdir="${svndir}"
        topsvndirs="${topsvndirs} ${svndir}"
    fi
done

# Display the status of each project.
for topsvndir in $topsvndirs ; do
    echo "project: ${topsvndir}"
    svn status --ignore-externals --show-updates "${topsvndir}"
    echo
done
