#!/bin/bash
#
# Remove orphaned packages and unneeded package files from Debian-like
# distributions.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/sbin.bash"

check_arg_count ${0} ${#} 0 0 '' ${1}

for package in $(deborphan) ; do
    apt-get --quiet=2 --yes purge "${package}"
done

apt-get --quiet=2 autoremove
apt-get --quiet=2 autoclean
