#!/bin/bash
# $Id$
#
# Look up the command line for the given Process ID (PID).
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2010 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 1 1 '<pid>' ${1}

cat /proc/${1}/cmdline
echo
