#!/bin/bash
#
# Count valid (HTTP 200 OK) web hits by domain name. Optionally filter log
# entries with a regular expression and, if given, discard entries that match
# a second regular expression.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/bin.bash"

check_arg_count ${0} ${#} 0 2 '[<regexp>] [<!regexp>]' ${1}

if [ -n "${1}" ] ; then
    regexp="${1}"
else
    # Match everything.
    regexp=".*"
fi

if [ -n "${2}" ] ; then
    deregexp="${2}"
else
    # Match nothing (blank lines shouldn't appear anyway).
    deregexp="^$"
fi

# Fetch valid hits from the log and extract the visitor's IP address. Look up
# the fully qualified domain name and truncate it. Count the number of hits from
# each domain, sorting the results in descending order by count.
egrep --no-filename 'HTTP\/.+?" 200' ${APACHE_LOG} | \
    egrep "${regexp}" | \
    degrep "${deregexp}" | \
    cut --fields 1 --delimiter ' ' | \
    logresolve | \
    truncate-domain | \
    sort | \
    uniq --count | \
    sort --numeric-sort --reverse | \
    column -t
