#!/bin/bash
# $Id$
#
# Count lines of PHP-related code in the current or given directory, excluding
# blank lines and single-line comments.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 0 1 '[<directory>]' ${1}

loc_dir=${1:-.}
extensions='php html css tpl'

for extension in $extensions; do
    # Ignore blank lines, single-line PHP comments, lines with only PHP code
    # tags, or single-line Smarty comments.
    loc=$(find "${loc_dir}" ${FIND_PATH_EXCLUDE} -or -type f -name "*.${extension}" -print0 | \
        degrep-rcs0 | \
        xargs -I{} --null egrep --invert-match '(^[[:space:]]*$)|(^[[:space:]]*(#|//))|(^[[:space:]]*(\?>)?(<\?)?[[:space:]]*$)|(^[[:space:]]*{\*.*\*}[[:space:]]*$)' {} | \
        wc --lines)

    if [ ${loc} -ne 0 ] ; then
        echo "${extension} ${loc}"
    fi
done
