#!/bin/bash
# $Id$
#
# Count invalid (HTTP 40x) web requests.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

# Delegate the task.
count-web-page-hits 'HTTP\/.+?" 40.'
