#!/bin/bash
#
# Generate descriptions of all Scripnix scripts formatted for Google Code wiki
# pages.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2010 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/sbin.bash"

check_arg_count ${0} ${#} 0 0 '' ${1}

today=$(date +%F)

echo -e "# Scripnix Script Descriptions\n"
echo -e "Summary descriptions of the scripts making up the Scripnix project. Phew. Try saying that five times fast.\n"
echo -e "The following was generated on ${today} by the \`describe-scripnix\` script.\n"

cd "${scriproot}"

while read script ; do
    name=$(echo "${script}" | cut --fields 2 --delimiter '/') 
    desc=$(${script} --help 2>&1)

    if [[ "${desc}" != Usage:* ]] ; then
        desc=$(sed --quiet --regexp-extended --expression '/^#$/,/^#$/p' "${script}" | sed --expression '/^#$/d' | cut --characters 3-)
        bname=$(basename "${script}")
        desc=$(echo -e "Usage: ${bname}\n\n${desc}")
    fi

    desc=$(echo "$desc" | sed --expression 's/ *$//' | sed --regexp-extended --expression 's/Usage: (.*)$/Usage: \`\1\`/')
    echo -e "### ${name}\n\n${desc}\n"
done < <(find . -maxdepth 1 -type f -executable -exec egrep --files-with-matches Scripnix {} \; | sort)
