#!/bin/bash
# $Id$
#
# Extract the script HTML file from one or more Celtx (celtx.com) archives into
# the current directory. Requires unzip.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2011 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/bin/bin.bash

check_arg_count ${0} ${#} 1 -1 '<file>[...]' ${1}

unzip=$(which unzip)

if [ ! -r "${unzip}" ] ; then
    echo_err "The unzip program is required for this command."
    exit 1
fi

while [ -n "${1}" ] ; do
    celtx_archive="${1}"

    # Ignore non-files
    [ ! -f "${celtx_archive}" ] && shift && continue

    # Extract the archive to a temporary directory and copy the script HTML file
    # to the current directory, using the archive name with an appended .html.
    extract_dir=$(mktemp --directory)
    unzip -d "${extract_dir}" -q "${celtx_archive}"
    /bin/cp --force "${extract_dir}/"script-*.html "${celtx_archive}.html"
    /bin/rm --force --recursive "${extract_dir}"
    shift
done
