#!/bin/bash
#
# Find all files larger than the given size (MB), or 100MB if not specified.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/sbin.bash

check_arg_count ${0} ${#} 0 1 '[<minimum-file-size-in-mb>]' ${1}

if [[ -n "${1}" ]] ; then
    min_size_kb=$(( ${1} * 1024 ))
else
    min_size_kb=$(( 100 * 1024 ))
fi

find / ${FIND_PATH_EXCLUDE} -or -type f -size "+${min_size_kb}k" -print | \
    xargs -I{} ls -l --block-size M --directory {} | \
    sort --key 5 --numeric-sort --reverse | \
    column -t
