#!/bin/bash
#
# Display all hard and soft links to the given file.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 1 1 '<file>' ${1}

inode=$(ls --inode "${1}" | cut --fields 1 --delimiter ' ')

# Find all the hardlinks.
links=$(find / -mount ${FIND_PATH_EXCLUDE} -or -type f -inum ${inode} -print 2>/dev/null)

# Find all the symlinks.
while read link linkpath linkedfile ; do
    # Normalize relative paths.
    slash=${linkedfile:0:1}

    if [ "${slash}" != '/' ] ; then
        linkedfile="${linkpath}/${linkedfile}"
    fi

    # Look up the inode of the linked file.
    linkedinode=$(ls --inode "${linkedfile}" 2>/dev/null | cut --fields 1 --delimiter ' ')

    if [ "${linkedinode}" == "${inode}" ] ; then
        links="${links} ${link}"
    fi 
# Find name, path, and linked-to-file for all symlinks outside of /proc.
done < <(find / ${FIND_PATH_EXCLUDE} -or -type l -printf '%p %h %l\n' 2>/dev/null)

for link in $links ; do
    ls -l --directory --color=tty "${link}"
done
