#!/bin/bash
# $Id$
#
# Search through the file contents in the specified directory (or the current
# directory if not given), and below, for lines that match the given regular
# expression.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 1 2 '[<directory>] <regexp>' ${1}

if [ ${#} -eq 2 ] ; then
    directory="${1}"
    regexp="${2}"
else
    directory="."
    regexp="${1}"
fi   

# Jump through hoops to find the regexp in all files, excluding RCS gunk. Use
# null-terminated lines throughout to avoid problems with filenames containing
# quotes. Trim any leading whitespace from the matching line.
find "${directory}" ${FIND_PATH_EXCLUDE} -or -type f -print0 | \
    degrep-rcs0 | \
    sort --zero-terminated | \
    xargs -I{} --null egrep --ignore-case --line-number --with-filename "${regexp}" {} | \
    sed --regexp-extended 's/:[[:space:]]+/:/'
