#!/bin/bash
#
# Find all files changed on the server within the last hour.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/sbin.bash"

check_arg_count ${0} ${#} 0 0 '' ${1}

find / ${FIND_PATH_EXCLUDE} -or -type f -mmin -60 -ls | sort -k9,10
