#!/bin/bash
# $Id$
#
# Find all files changed on the server within the last hour.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/sbin.bash

check_arg_count ${0} ${#} 0 0 '' ${1}

find / ${FIND_PATH_EXCLUDE} -or -type f -mmin -60 -ls | sort -k9,10
