#!/bin/bash
# $Id$
#
# Translate the given filenames (via stdin) into their equivalent,
# filesystem-safe, hyphenated versions.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/bin/bin.bash

check_arg_count ${0} ${#} 0 0 '' ${1}

# Characters that shouldn't really appear in a filename.
unsafe="\`~\!@#$%^&*()+={}|[]\\:;\"\'<>?,/ \t"

while read name; do
    # Replace the unsafe characters with hyphens, removing redundant sequential
    # hyphens and any hyphen at the beginning or end of the name.
    echo "${name}" | \
        tr "${unsafe}" '[-*]' | \
        sed --regexp-extended --expression 's/-{2,}/-/g' | \
        sed --regexp-extended --expression 's/^-|-$//g'
done
