#!/bin/bash
#
# Translate the given filenames (via stdin) into their equivalent,
# filesystem-safe, hyphenated versions.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 0 0 '' ${1}

# Characters that shouldn't really appear in a filename.
unsafe="\`~\!@#$%^&*()+={}|[]\\:;\"\'<>?,/ \t"

while read name; do
    # Replace the unsafe characters with hyphens, removing redundant sequential
    # hyphens and any hyphen at the beginning or end of the name.
    echo "${name}" | \
        tr "${unsafe}" '[-*]' | \
        sed --regexp-extended --expression 's/-{2,}/-/g' | \
        sed --regexp-extended --expression 's/^-|-$//g'
done
