#!/bin/bash
#
# Detects whether this terminal is a remote SSH connection. Exit code will be
# zero if it is.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2010 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/bin.bash"

check_arg_count ${0} ${#} 0 0 '' ${1}

# This is a remote connection if the top-level parent process is the SSH daemon.
parent=$(command-for-pid $(top-level-parent-pid))
match=$(echo "${parent}" | egrep sshd)
test -n "${match}"
