#!/bin/bash
#
# Extract a unique list of the first column of the given input. Optionally, use
# the specified delimiter instead of space.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/bin.bash"

check_arg_count ${0} ${#} 0 1 '[<delimiter>]' ${1}

if [ ${#} -eq 1 ] ; then
    delimiter="${1}"
else
    delimiter=' '
fi

cat - | cut --fields 1 --delimiter "${delimiter}" | sort --unique
