#!/bin/bash
# $Id$
#
# Locate matching files and display identical files grouped together.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 1 1 '<regexp>' ${1}

prehash=''

while read hash_line; do
    hash=$(echo $hash_line | awk '{ print $1 }')
    
    # Insert an empty line when the hashes change (unless this is the first hash).
    if [ "${hash}" != "${prehash}" ] && [ "${prehash}" != '' ]; then
        echo
    fi
    
    echo $hash_line | awk '{ print $2 }'
    prehash=$hash
done < <(locate -r ${1} | degrep-rcs | include-filetype f | xargs -I{} md5sum {} | sort)
