#!/bin/bash
#
# Locate matching files and display in coloured long-list format.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/bin.bash"

check_arg_count ${0} ${#} 1 1 '<regexp>' ${1}

# Ignore source control droppings.
locate -r ${1} | degrep-rcs | xargs -I{} ls -l --directory {} | column -t
