#!/bin/bash
# $Id$
#
# Locate matching files and display in coloured long-list format.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 1 1 '<regexp>' ${1}

# Ignore source control droppings.
locate -r ${1} | degrep-rcs | xargs -I{} ls -l --directory {} | column -t
