#!/bin/bash
#
# Export the given Subversion project into a gzipped tarball in the current
# directory, named for the project, version, and Subversion revision number.
# 
# For example, to package version 1.0 of the Scripnix project into a file
# named scripnix-1.0.XX.tgz ("XX" will be replaced with the Subversion revision
# number):
# 
# package-svn-project scripnix 1.0 https://github.com/yukondude/Scripnix/svn/trunk/
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 3 3 '<project> <version> <svn-url>' ${1}

project="${1}"
version="${2}"
url="${3}"

revision=$(svn info "${url}" | egrep '^Revision' | awk '{print $NF}')
export_name="${project}-${version}.${revision}"

if svn export --quiet "${url}" "${export_name}" ; then
    tar --create --gzip --file "${export_name}.tgz" "${export_name}"
    rm --force --recursive "${export_name}"
fi
