#!/bin/bash
#
# Remove all but a given number of files that match the provided filespec
# (in quotes if wildcards are specified), so that the remaining files have the
# most recent modification times. If the filespec is omitted, perform the
# operation on all files in the current directory.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2010 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/bin.bash"

check_arg_count ${0} ${#} 1 2 '<number-to-keep> [<filespec>]' ${1}

keep="${1}"
keep=$(( keep+1 ))
filespec="${2:-*}"

ls -1t ${filespec} | tail --lines +"${keep}" | xargs -I{} rm --force {}
