#!/bin/bash
# $Id$
#
# Repeat a simple command every N seconds.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 2 -1 '<delay> <command...>' ${1}

delay=${1}
shift

while true ; do
    date
    ${*}
    echo
    sleep ${delay}
done
