#!/bin/bash
# $Id$
#
# Repeat a simple command every N seconds.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 2 -1 '<delay> <command...>' ${1}

delay=${1}
shift

while true ; do
    date
    ${*}
    echo
    sleep ${delay}
done
