#!/bin/bash
#
# Restart the NTP time service, forcing a time synchronization while the
# service is stopped.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriproot}/sbin.bash"

check_arg_count ${0} ${#} 0 0 '' ${1}

# Slow and silent.
control-service ntp stop >/dev/null
sleep 5
ntpdate "${NTPDATE_SERVER}" >/dev/null
sleep 5
control-service ntp start >/dev/null
