#!/bin/bash
# $Id$
#
# Synchronize all mirrored Subversion repositories on the local machine. The
# script assumes that all such repositories have a suffix of "mirror".
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/bin/bin.bash

check_arg_count ${0} ${#} 0 0 '' ${1}

for repository in $(find "${SVN_REPO_DIR}/" -maxdepth 1 -mindepth 1 -type d -name '*mirror' -print) ; do
    repository=$(basename "${repository}")
    echo "Synchronizing ${repository}"
    svnsync sync "svn://localhost/${repository}"
done
