#!/bin/bash
# $Id$
#
# Truncate a fully qualified domain name by removing the host name part. Only
# the first column of the input is truncated.
#
# This file is a part of Scripnix <https://github.com/yukondude/Scripnix/>.
# Written in 2008 by Dave Rogers <yukondude.com>
# This is free and unencumbered software released into the public domain.
# Refer to the LICENCE file for the not-so-fine print.

scriproot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $scriproot/bin.bash

check_arg_count ${0} ${#} 0 0 '' ${1}

# Awk script uses "." for field delimiter. Truncate IP addresses to first two
# quads. Truncate Country TLDs to last two or three terms. Truncate all
# remaining to last two terms.
truncate=$(cat <<'EOF'
BEGIN {FS="."}
/[0-9]$/ {print $1 "." $2 ".0.0/16"; next}
/\.(com|org|net|edu|gov|mil|[^.][^.])\.[^.][^.]$/ {print $(NF-2) "." $(NF-1) "." $NF; next}
{print $(NF-1) "." $NF}
EOF
)

while read fqdn remaining; do
    truncated_fqdn=$(awk "${truncate}" <(echo "${fqdn}"))
    echo $truncated_fqdn $remaining
done
