#!/bin/bash
# $Id$
#
# Archive each MySQL database under the $ARCHIVE_MYSQL_DIR directory separately
# into a compressed tarball in the $ARCHIVE_DIR directory.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/sbin/sbin.bash

# Prepare the temporary dump directory and restrict access to the owner.
tmp_dir=$(mktemp -dt 'archive-XXXXXXXX')
chmod go= "${tmp_dir}"

# Dump each database separately. Makes a single DB easier to recover rather than
# using the mysqldump --all-databases option.
for database in $(find "${MYSQL_DB_DIR}/" -maxdepth 1 -mindepth 1 -type d -print) ; do
    database=$(basename "${database}")
    mysqldump --opt "${database}" | gzip > "${tmp_dir}/${database}.sql.gz"
done

# Prepare permissions on the dump file, whether or not it already exists.
dump_file="${ARCHIVE_DIR}/${MYSQL_DUMP_FILE}"
touch "${dump_file}"
chmod g=r,o= "${dump_file}"

# Combine the dump files into a single tarball and clean up temporary files.
cd "${tmp_dir}"
tar --create --file "${dump_file}" *gz 2>/dev/null
cd /
rm --force --recursive "${tmp_dir}"
