#!/bin/bash
# $Id$
#
# Archive a dump of the Subversion respository under the $ARCHIVE_SVN_DIR
# directory into a compressed tarball in the $ARCHIVE_DIR directory.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/sbin/sbin.bash

# Prepare the temporary dump directory and restrict access to the owner.
tmp_dir=$(mktemp -dt 'archive-XXXXXXXX')
chmod go= "${tmp_dir}"

# Dump each repository.
svnadmin dump "${SVN_REPO_DIR}" --quiet | gzip > "${tmp_dir}/${SVN_DUMP_FILE}"

# Prepare permissions on the dump file, whether or not it already exists.
dump_file="${ARCHIVE_DIR}/${SVN_DUMP_FILE}"
touch "${dump_file}"
chmod g=r,o= "${dump_file}"

# Combine the dump files into a single tarball and clean up temporary files.
mv --force "${tmp_dir}/${SVN_DUMP_FILE}" "${dump_file}" 2>/dev/null
rm --force --recursive "${tmp_dir}"
