#!/bin/bash
# $Id$
#
# Archive a dump of each Subversion respository under the $SVN_REPO_DIR
# directory into a compressed tarball in the $ARCHIVE_DIR directory.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/sbin/sbin.bash

# Prepare the temporary dump directory and restrict access to the owner.
tmp_dir=$(mktemp -dt 'archive-XXXXXXXX')
chmod go= "${tmp_dir}"

# Dump each repository.
for repository in $(find "${SVN_REPO_DIR}/" -maxdepth 1 -mindepth 1 -type d -print) ; do
    repository=$(basename "${repository}")
    svnadmin dump "${SVN_REPO_DIR}/${repository}" --quiet | gzip > "${tmp_dir}/${repository}.svn.gz"
done

# Prepare permissions on the dump file, whether or not it already exists.
dump_file="${ARCHIVE_DIR}/${SVN_REPOSITORIES_DUMP_FILE}"
touch "${dump_file}"
chmod g=r,o= "${dump_file}"

# Combine the dump files into a single tarball and clean up temporary files.
cd "${tmp_dir}"
tar --create --file "${dump_file}" *gz 2>/dev/null
cd /
rm --force --recursive "${tmp_dir}"
