#!/bin/bash
# $Id$
#
# Archive all directories symlinked under $ARCHIVE_PATHS to the $ARCHIVE_DIR
# directory using the name of the symlink as the compressed tarball's filename.
#
# This file is a part of Scripnix <http://code.google.com/p/scripnix/>.
# Written in 2007 by Dave Rogers <thedude-strudel-yukondude-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/sbin/sbin.bash

# With each symlink in the archive-paths/ directory, process the link's name
# and target (linkpath).
while read linkname linkpath ; do
    # Format archive filename.
    linkname=$(basename "${linkname}")
    archive_file="${ARCHIVE_DIR}/${linkname}.tgz"
    
    # Prepare archive file permissions before creating.
    touch ${archive_file}
    chmod 0640 ${archive_file}
    
    # Create (compressed) archive file.
    tar -zcpf "${archive_file}" "${linkpath}" 2>/dev/null
done < <(find "${ARCHIVE_PATH_DIR}" -type l -printf '%p %l\n' 2>/dev/null)
