#!/bin/bash
# $Id$
#
# Execute the given rc init script with the given action.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/sbin/sbin.bash

check_arg_count ${0} ${#} 1 2 '<rc init script> <action>' ${1}

function show_available_rc() {
    # Display the list of executable scripts in the rc init directory.
    echo_err
    echo_err "The following rc init scripts are available in ${RC_DIR}:"
    find "${RC_DIR}/" -maxdepth 1 -type l -o -type f -perm -u+x -exec basename {} \; | sort | column >&2
}

if [[ -x "/usr/sbin/service" ]] ; then
    # Run the built-in service command if it exists.
    /usr/sbin/service "${@}"

    if [[ ${?} -eq 1 ]] ; then
        # Unknown script so show list.
        echo_err "Unknown rc init script: ${RC_DIR}/${1}."
        show_available_rc
    fi
else
    # Otherwise, run the init script manually.
    if [[ ${#} -ge 1 && ! -x "${RC_DIR}/${1}" ]] ; then
        # Unknown script so show list.
        echo_err "Unknown rc init script: ${RC_DIR}/${1}."
        show_available_rc
        exit 1
    fi

    # Run the damned script already.
    ${RC_DIR}/${1} ${2}
fi
