#!/bin/bash
# $Id$
#
# Find all files larger than the given size (MB), or 100MB if not specified.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2008 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/sbin/sbin.bash

check_arg_count ${0} ${#} 0 1 '[<minimum-file-size-in-mb>]'

if [[ -n "${1}" ]] ; then
    min_size_mb="${1}"
else
    min_size_mb=100
fi

find / ${FIND_PATH_EXCLUDE} -or -type f -size "+${min_size_mb}M" -print | \
    xargs -I{} ls -l --block-size M --directory {} | \
    sort --key 5 --numeric-sort --reverse | \
    column -t
