#!/bin/bash
# $Id$
#
# Find all files changed on the server within the last hour.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2007 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/sbin/sbin.bash

find / -type f -mmin -60 -ls | degrep '\/(proc|dev|sys)\/' | sort -k9,10
