#!/bin/bash
# $Id$
#
# Find all files changed on the server within the last hour.
#
# This file is a part of Scripnix <http://scripnix.googlecode.com/>.
# Written in 2007 by Dave Rogers <yukondude-strudel-gmail-fullstop-com>.
# This script is released into the Public Domain.

source /usr/local/sbin/sbin.bash

find / ${FIND_PATH_EXCLUDE} ${FIND_RCS_EXCLUDE} -type f -mmin -60 -ls | sort -k9,10
